version: '2.1'
services:
  mysql:
      build: ./db
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'cs160'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
      command: --default-authentication-plugin=mysql_native_password
      healthcheck:
          test: "exit 0"
  
  myawesomeapp:
      build: .
      depends_on:
          mysql:
              condition: service_healthy
      entrypoint:
          - /usr/local/bin/docker-entrypoint.sh
      ports:
          - "3000:3000"